"""
Snakemake pipeline for APAlyzer.
For help see: https://snakemake.readthedocs.io/en/stable/index.html.
"""

import os


LOG_DIR = os.path.join(config["out_dir"], config["logs_subdir"],"")

include: "rules/preprocessing.smk"
include: "rules/main.smk"
include: "rules/postprocessing.smk"

#-------------------------------------------------------------------------------
localrules: finish


rule finish:
    """
    Rule that specifies the final output.
    """
    input:
        final = rules.postprocessing.output.out_postprocessing
        #final = os.path.join(config["out_dir"],"differential_challenge_output.tsv")

#-------------------------------------------------------------------------------
# How did it go?
#-------------------------------------------------------------------------------
onsuccess:
    print("Workflow finished, no error")

onerror:
    print("An error occurred, check log at %s." % {log})
