"""Snakemake pipeline for Dapars2.
For help see: https://snakemake.readthedocs.io/en/stable/index.html.
"""

import pandas as pd
import os
import sys



samples = pd.read_csv(config["samples"]).set_index("sample", drop=False)

out_suffixes = [config["out_id_bed_suffix"], config["out_rel_bed_suffix"]]

LOG_DIR = os.path.join(config["out_dir"], config["logs_subdir"],"")

include: "rules/preprocess_annotation.smk"
include: "rules/preprocess_seq.smk"
include: "rules/dapars2.smk"
include: "rules/get_output_beds.smk"

#-------------------------------------------------------------------------------
localrules: finish


rule finish:
    """Rule that specifies the final output.
    """
    input:
        final = expand(
            os.path.join(config["out_dir"], "{sample}" + "{suffixes}"),
            sample=samples.index.values,
            suffixes=out_suffixes)






#-------------------------------------------------------------------------------
# How did it go?
#-------------------------------------------------------------------------------
onsuccess:
    print("Workflow finished, no error")

onerror:
    print("An error occurred, check log at %s." % {log})
