"""
Snakemake pipeline for APAlyzer.
For help see: https://snakemake.readthedocs.io/en/stable/index.html.
"""

import pandas as pd
import os
import sys

df = pd.read_csv(config["samples"], index_col="sample")
samples = df.index

LOG_DIR = os.path.join(config["out_dir"], config["logs_subdir"],"")

include: "rules/genome_preprocessing.smk"
include: "rules/quantification.smk"
#include: "rules/differential_usage.smk"

#-------------------------------------------------------------------------------
localrules: finish


rule finish:
    """
    Rule that specifies the final output.
    """
    input:
        final = os.path.join(config["out_dir"],"siControl_R1_quant_APAlyzer.csv")
        #diff_usage = expand(os.path.join(config["out_dir"],"differential_usage_APAlyzer.csv"))


#-------------------------------------------------------------------------------
# How did it go?
#-------------------------------------------------------------------------------
onsuccess:
    print("Workflow finished, no error")

onerror:
    print("An error occurred, check log at %s." % {log})
