"""Snakemake pipeline for PAQR.
For help see: https://snakemake.readthedocs.io/en/stable/index.html.
"""

import pandas as pd
import os
import sys
       

samples = pd.read_table(config["PAQ_samples_table"], header=0, index_col=0)


include: "rules/create_tandem_pas.smk"
include: "rules/paqr.smk"
include: "rules/postprocess.smk"


localrules: create_log_dir, get_TPAS_scripts, get_PAQR_scripts, finish

rule finish:
    """Rule that specifies the final output. 
    """
    input:
        BED_quantification = expand(os.path.join(
                config["PAQ_outdir"],
                "{sample}" + config["challenge_code"] + config["method"] + config["outcode"] + ".bed"),
                sample = samples.index)




#-------------------------------------------------------------------------------
# How did it go?
#-------------------------------------------------------------------------------
onsuccess:
    print("Workflow finished, no error")

onerror:
    print("An error occurred, check log at %s." % {log})