# Configuration file for snakemake pipeline

# Dataset samples
# samples: "config/[SAMPLES].csv"
samples: "config/samples.csv"
out_dir: "results"
gtf: "Mus_musculus.GRCm38.99.gtf.gz"
# gff: "../../../tests/test_data/gencode_2genes_noChr.vM18.annotation.gff3"
genome_name: "gencode_2genes_noChr.vM18.annotation"
# Parameters
# define method specific parameters here

# Settings
envs: "envs"
local_log: "logs/local_log"
cluster_log: "logs/cluster_log"