# Configuration file for snakemake pipeline

# Path to run-specific sample table of | sample | bam
sample_file: "config/samples.csv"

# Path to main output directory for run
out_dir: "results/"

# Path to GTF annotation file
#gtf: "Mus_musculus.GRCm38.99.gtf.gz"
gtf: "../../../tests/test_data/gencode_2genes_Chr_prefix.vM18.annotation.gtf"
gtf_organism: "Mus_musculus"
gtf_genome_version: "GRCm38"
gtf_ensemble_version: 93

genome_name: "gencode_2genes_noChr.vM18.annotation"

logs_subdir: logs/

# Settings
envs: "envs"
local_log: "logs/local_log"
cluster_log: "logs/cluster_log"
