"""Snakemake pipeline for Dapars2.
For help see: https://snakemake.readthedocs.io/en/stable/index.html.
"""

import pandas as pd
import os
import sys

configfile:"config/config.DaPars2.yaml"

samples = pd.read_csv(config["samples"]).set_index("sample", drop=False)

LOG_DIR = os.path.join(config["out_dir"], config["logs_subdir"],"")

include: "rules/preprocess_annotation.smk"
include: "rules/preprocess_seq.smk"
include: "rules/dapars2.smk"
include: "rules/get_identification_bed.smk"

#-------------------------------------------------------------------------------
localrules: finish


rule finish:
    """Rule that specifies the final output.
    """
    input:
        final = expand(
            os.path.join(config["out_dir"], "{sample}" + config["out_bed_suffix"]),
            sample=samples.index.values)
        # OUT1 = os.path.join(config["out_dir"],  "DaPars2_result_chr")
        # os.path.join(config["out_dir"], "01_DaPars2.BED")






#-------------------------------------------------------------------------------
# How did it go?
#-------------------------------------------------------------------------------
onsuccess:
    print("Workflow finished, no error")

onerror:
    print("An error occurred, check log at %s." % {log})
