# Configuration file for APAlyzer snakemake pipeline

# Note: paths in this config file are relative to the
#       working directory APAlyzer_snakemake

# Path to run-specific sample file
sample_file: "config/samples.csv"

# Apalyzer isn't compatible with identification challenge. Always set this value to False
run_identification: False

# Apalyzer isn't compatible with quantification challenge. Always set this value to False
run_quantification: False

# Apalyzer is only compatible with differential challenge. Always set this value to True
run_differential: True

# Path to output directory for run. Default: results/
out_dir: "results/"
# Output file name, ends with .tsv
differential_output_file: "differential_challenge_output.tsv"
# Name of log directory to be placed in out_dir. Default: logs/
logs_subdir: "logs/"

# Path to GTF annotation file
gtf: "../../tests/test_data/gencode_2genes_noChr.vM18.annotation.gtf"
# GTF annotation file organism, genome version, and ensemble version details
gtf_organism: "Mus_musculus"
gtf_genome_version: "GRCm39"
gtf_ensemble_version: "103"

# Read cutoff, default: 0
# This is the minimum read count for UTRs. When set to some number
# greater than 0, this allows us to exclude UTRs with small number of reads
# to reduce noise that stems from genes with low read coverages
read_cutoff: 0

# strand type of the bam file;
#  "forward" is forwad sequencing,
#  "invert" is reverse sequencing,
#  "NONE" is non-strand specific,
strandtype: "forward"

# APAlyzer docker container
container: "docker://apaeval/apalyzer:1.0.6"
