##### BASE IMAGE #####
FROM python:2.7.14-slim-stretch as build

##### METADATA #####
LABEL base.image="python:2.7.14-slim-stretch"
LABEL software="mountainClimber"
LABEL software.version="65132f2"
LABEL software.description="mountainClimber identifies alternative transcription start and polyadenylation sites in RNA-Seq"
LABEL software.website="https://github.com/gxiaolab/mountainClimber"
LABEL software.documentation="https://github.com/gxiaolab/mountainClimber/blob/65132f210d17e5313198e4a0f83f737e57de6b53/README.md"
LABEL software.license="Apache License 2.0"
LABEL maintainer="alexander.kanitz@alumni.ethz.ch"
LABEL maintainer.organisation="APAeval"
LABEL maintainer.license="https://raw.githubusercontent.com/gxiaolab/mountainClimber/65132f210d17e5313198e4a0f83f737e57de6b53/LICENSE"

##### VARIABLES #####
ENV COMMIT 65132f2
ENV PACKAGES build-essential git libz-dev
ENV PACKAGES_PIP scipy==0.15.1 numpy==1.10.4 peakutils==1.0.3 \
  scikit-learn==0.18.1 pysam==0.9.0 pybedtools==0.6.2 matplotlib==2.2.5

#### SET WORKING DIRECTORY ####
WORKDIR /app

#### INSTALLATION ###
RUN apt-get update
RUN apt-get install -y --no-install-recommends ${PACKAGES}
RUN pip install cython
RUN pip install ${PACKAGES_PIP}
RUN git clone https://github.com/gxiaolab/mountainClimber.git
RUN cd mountainClimber \
  && git reset --hard ${COMMIT} \
  && chmod +x src/*

##### CLEAN IMAGE ####
FROM python:2.7.14-slim-stretch
COPY --from=build /app/mountainClimber/src/* /usr/bin/
COPY --from=build /usr/local/lib/python2.7/site-packages/ /usr/local/lib/python2.7/site-packages/
RUN mkdir /user && ln -s /usr/local/bin /user/bin

##### COMMAND / ENTRY POINT ####
CMD ["bash"]
