import pandas as pd
import sys
import argparse

def main(roar_results_path, output_tsv):
    '''
    '''

    df = pd.read_csv(roar_results_path, sep="\t")

    # Roar does combinatorial comparisons of individual samples
    # 'pval' reports multiplication of each of these comparisons, which will pretty much always result in an extremely small pval
    # Select the smallest p-value across all comparisons to report in output
    df.loc[:, "min_pval"] = df.loc[:, df.columns.str.startswith("pvalue_")].min(axis="columns")

    df[["gene_id", "min_pval"]].to_csv(output_tsv,
                                       header=False,
                                       index=False,
                                       sep="\t")



if __name__ == '__main__':

    descrpn = "Generate APAeval differential challenge output file from TSV of Roar output results"

    parser = argparse.ArgumentParser(description=descrpn)

    parser.add_argument("-i",
                        required=True,
                        type=str,
                        help="Path to input Roar results TSV file (e.g. generated by Roar.R)")

    parser.add_argument("-o",
                        required=True,
                        type=str,
                        help="Name of/path to differential challenge output file")

    if len(sys.argv) == 1:
        parser.print_help()
        parser.exit()

    args = parser.parse_args()

    main(args.i, args.o)
